language: node_js
node_js:
- 6.10.2
deploy:
  provider: heroku
  api_key:
    secure: "kQdajBlJ7oiBnzShiPUVRnStwyL5o3UwxQjub7cnRaPAhBp81SOgen77ZIVkmeRpKoa2UGKD3nkxVjNHRqeZX3QXVolDNzlpDKfPkF/BUd7oPbi0a+hrWWjBo+q5R8y1qf76TZFUGU+VXdRfFK7JnSU0vc28LQz+qRMLEAFwPK0LZRZ5/65ou4JP/xJozITxIM4Bt1QZr7nofE9S2yG3tXBOCV35Vy3xzmfNYL3csD/AkqWwx2bSqJKhBSyIY/d8f/vYWD9aTcAupdPYtx8aFIB2oXbbxJFDaufOS06ZgiuTMhVC11qH5JIedUEEEbHHry/NuJDIHIHm8jRs3KXMUEqh3qTrto8baJMW45PkhvmTfpYMrOkRD/ZY3O6b5zEm/rGuf7/St3gcVPZ8r22rthZtdRHudEeGyx8zFvoXcD2tvaGeeO4cOceyFUQyIA+IBLy7kX6nmS3rmgwQ1b5+20fzZMFaWhtCu2PLizDbGtwaxXO2bivJpouj3yahhKnAPH03yYaKzINesz2fOUUyB1kZ1i7a7f32B6ge+5pW0e6mdqdVuKxQILT7md8NZ2VY34CTtR+sRyVM7+tlTC9h9OU2OUAQ3J0nkwi7vbmhcmO4eGznf0jrglOc+YveQxTiEBH18p/5t4gWUJGZTaEqMNC8S7HunkeujgCZIdGPoI0="
  app: pond-game
