language: node_js
node_js:
- 6.10.2
deploy:
  provider: heroku
  api_key:
    secure: BdJHnomKb/UCIRPu21No7M30yHcj1Kxstf55Efe60gqTOsXcg9m4UlEdjABtYO/4KFN4udZj84XVrCvs1uBNQyXb3k2pOm0v2mKdTjqRwN/lHEydDcdrW5a8DcnzK7pl7/sxkGiI3UCRbO38TdkF7NS5s3qmNxFjQS3/yCLrefhI2FaO1e5UP8z3GHaOzLbXy24OmBIZlKpgwhlj9fxbi0jsfhy4dzYW2t0vFIz1F+xTygb+9kxr/Nj2qyrfhVeCJU0iH8Kjtt694zkq7KOoK8GcLHR+2TjRUc5XrYiYODIX212xMOu2yhd3nkHD8ngVntyYXN5BvMJLKQ/iWwCfJSYTEfLrn4BkHcevy8DH+zcYYm5sQSb6pznDuTYmHI9ddR06v5yoq2ZW58JK+lflJT95RXIeQ+BOpY2PG4cYE+QYu8RJAr9yUxAx0Ohp8IJzpC0P+3zPrr52RiUhuSYsa+Zv3edmyfmY040U93RstAoCOuW1544eAVtHX3jqk4ULCf01QAGFk/hr9n7t/lsJ4GqXR0iMZE9Wt9k+KMmUQ4gxSwHmgr/Kfb/11022J61ZWlMIxi44iOTzISMeyghBVVCRNDsp86ybG8c1hWMw/hy80BFemlBSxt16fZ4vaVhFfRsX8rT7ziwwZeZBP8Xb9pTX0Gr7yUMRW3KNqeBzWEs=
  app: pond-game
