language: node_js
node_js:
- 6.10.2
deploy:
  provider: heroku
  api_key:
    secure: imYUJCHML7ofIAsNuZcM/urGPwTd9WCAol3tdmDROczT8hxG3zkOsXHm7J+3BqKQKnyhjp3nx5EKIDhsUWcO4/XQ4LEiaCM8mow/EWhH1sMvQeneYyESvng5T0kyEEj+0guoOZZ/z1nFcFShJqDmr4VNmoMNh2hUoWlYJ3yj/B963LQgMWSMkCxeTisjOTzhEsfIcwVl9wpIOobl47Q9KUSWYCv4t4EonCxyhq/8zZRjIW33K78nr3dL3lw4RjaoNpsZbRXfNx5ZKLIiwaEZJN+P9VgaCzUUOv26gk5ZRe1fKDJoc0OzxoXp2W0NlOy9RKHdzTwXT1wzyihNfp5b32PDn5w0oRVobcFbP8y0IAOVQlBUk3EbJHl8rGLkTYwSQm4A/xBR5vSPLetyYjN+mMwxmK5Cyfa4wNAU7S9PeTR+1rdjry4d/IP12zqU/5pcZOvZzrLGI3lJHS1VziIhdx+sVlfNU1pU84VZu9WknX+LdkP0nv14MKbwdudMrFQiNptfDigf1o5BsWAcnwYJtw3axOEr0CjYKmoixrilEEtHT3rBkil2YjhLp+666bsdU6XIUOuH+bhZ/kf2LvXr7KyaNFlnhTHfYzorlByxuzbYI9+WWwuvAoI7BfxtwcLcUOu/ZPIxRhwbxVDIcclY8r39IHxWzUmWM+BK3+Qwya8=
  app: pond-game
